---
title: "Stable_DESeq-boxplots_Pdam"
author: "Mike Connelly"
date: "10/24/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/computing/projects/EAPSI_Pocillopora_LPS")
```
## Setup packages and working directories
```{r packages, error=FALSE, warning=FALSE, message=FALSE}
library("DESeq2")
library("tidyverse")
library("ggplot2")
library("ggrepel")
library("RColorBrewer")
library("scales")
library("ggpubr")
library("grid")
```
Set colors and shapes for ggplot options
```{r}
theme_set(theme_bw())
colshapes <- c(16, 17, 15, 18)
condcolors_LPS <- c("#0000FF", "#FF66FF")
colcolors <- c("olivedrab3", "springgreen", "deepskyblue", "skyblue")
condfillcolors_LPS <- c("#99CCFF", "#FFCCFF")
```

Create ggboxplot functions
```{r}
ggboxplot <- function(gene, res, samples) {
titlegene <- grep(gene, res$ID)
plotTitle <- res$GeneInfo[titlegene]
gplot <- plotCounts(dds_LPS, gene = gene, intgroup = "Treatment", returnData = TRUE)
print(ggplot(gplot, aes(x=Treatment, y=count, color=samples$Treatment)) 
      + geom_boxplot(aes(fill=samples$Treatment), show.legend = FALSE) 
      + geom_point(aes(shape = samples$Colony), size = 3, show.legend = FALSE) 
      + scale_color_manual(values=condcolors_LPS) + scale_fill_manual(values = condfillcolors_LPS) + scale_shape_manual(values = colshapes) + scale_y_continuous(trans = log2_trans(), breaks = trans_breaks("log2", function(x) 2^x),
    labels = trans_format("log2", math_format(2^.x)))
      + ggtitle(plotTitle))
}
```
```{r}
ggboxplot_geno <- function(gene, res, samples) {
titlegene <- grep(gene, res$ID)
plotTitle <- res$GeneInfo[titlegene]
gplot <- plotCounts(dds_LPS, gene = gene, intgroup = "Treatment", returnData = TRUE)
print(ggplot(gplot, aes(x=Treatment, y=(count+0.5), color=samples$Treatment)) 
      + geom_boxplot(aes(fill=samples$Treatment), show.legend = FALSE) 
      + geom_point(aes(shape = samples$Colony), size = 3, show.legend = FALSE) 
      + facet_grid(.~samples$Colony)
      + scale_color_manual(values=condcolors_LPS) + scale_fill_manual(values = condfillcolors_LPS) + scale_shape_manual(values = colshapes) 
      + scale_y_continuous(trans = log2_trans(), breaks = trans_breaks("log2", function(x) 2^x),
    labels = trans_format("log2", math_format(2^.x)))
      + ggtitle(plotTitle))
}
```
```{r}
ggboxplot_geno("pdam_00002773", res_LPS, stable_samples_LPS)
ggboxplot("pdam_00023321", res_LPS, stable_samples_LPS)
ggboxplot("pdam_00016279", res_LPS, stable_samples_LPS)
```


```{r}
gglistplot <- function(genelist, dds, res, samples) {
for (gene in genelist) {
titlegene <- grep(gene, res$ID)
plotTitle <- res$GeneInfo[titlegene]
gplot <- plotCounts(dds, gene = gene, intgroup = "Treatment", returnData = TRUE)
print(ggplot(gplot, aes(x=Treatment, y=count, color=samples$Treatment)) 
      + geom_boxplot(aes(fill=samples$Treatment), show.legend = FALSE) 
      + geom_point(aes(shape = samples$Colony), size = 3, show.legend = FALSE) 
      + scale_color_manual(values=condcolors_LPS) + scale_fill_manual(values = condfillcolors_LPS) + scale_shape_manual(values = colshapes) + scale_y_continuous(trans = log2_trans(), breaks = trans_breaks("log2", function(x) 2^x),
    labels = trans_format("log2", math_format(2^.x)))
      + ggtitle(plotTitle))
}
}
```
```{r}
gglistplot_genotype <- function(genelist, dds, res, samples) {
for (gene in genelist) {
titlegene <- grep(gene, res$ID)
plotTitle <- res$GeneInfo[titlegene]
gplot <- plotCounts(dds, gene = gene, intgroup = "Treatment", returnData = TRUE)
print(ggplot(gplot, aes(x=Treatment, y=count, color=samples$Treatment)) 
      + geom_boxplot(aes(fill=samples$Colony), show.legend = FALSE) 
      + geom_point(aes(shape = samples$Colony), size = 3, show.legend = FALSE) 
      + facet_grid(.~samples$Colony)
      + scale_color_manual(values=condcolors_LPS) + scale_fill_manual(values = colcolors) + scale_shape_manual(values = colshapes) + scale_y_continuous(trans = log2_trans(), breaks = trans_breaks("log2", function(x) 2^x),
    labels = trans_format("log2", math_format(2^.x)))
      + ggtitle(plotTitle))
}
}
```

Edit gene name
```{r}
res_LPS$IDGeneInfo <- gsub( "pdam_00002776 unknown function", "pdam_00002776 Basic helix-loop-helix family member E40", res_LPS$IDGeneInfo)
res_LPS$IDGeneInfo <- gsub( "pdam_00002776 Basic helix-loop-helix family member E40 function", "pdam_00002776 Basic helix-loop-helix family member E40", res_LPS$IDGeneInfo)
```

for use in LPS paper with proper theme and formatting
```{r}
gglistplot_genotype <- function(genelist, dds, res, samples) {
for (gene in genelist) {
titlegene <- grep(gene, res$ID)
plotTitle <- rownames(res)[titlegene]
plotsub <- gsub("pdam_[0123456789]{8} ", "", res$GeneInfo[titlegene])
###
gplot <- plotCounts(dds, gene = gene, intgroup = "Treatment", returnData = TRUE)
gbplot <- ggplot(gplot, aes(x=Treatment, y=count, color=samples$Treatment)) +
  geom_boxplot(aes(fill = samples$Treatment), show.legend = FALSE) +
  geom_point(aes(shape = samples$Colony), size = 3, show.legend = FALSE) +
  facet_grid(.~samples$Colony) +
  ### add interaction line between genotypes
  stat_summary(fun=mean, geom="path", colour="black", size=0.8, aes(group = samples$Colony)) +
  stat_summary(fun=mean, geom="point", colour="black", size=3, aes(shape = samples$Colony, group = samples$Colony), show.legend = FALSE) +
  ###
  scale_color_manual(values=condcolors_LPS) + scale_fill_manual(values = condfillcolors_LPS) + scale_shape_manual(values = colshapes) +
  scale_y_continuous(trans = log2_trans(), breaks = trans_breaks("log2", function(x) 2^x), labels = trans_format("log2", math_format(2^.x)))  + 
  ggtitle(plotTitle, subtitle = plotsub) +
  ylab("gene count") +
  theme(plot.title = element_text(size = 10, face = "bold"),
        plot.subtitle = element_text(size = 6),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_text(size = 10),
        axis.text.y = element_text(angle = 0, size = 10),
        strip.text = element_text(size = 10),
        strip.background = element_rect(fill = "light grey"))
print(gbplot)
###
g_bplot <- ggplot_gtable(ggplot_build(gbplot))
strip_both <- which(grepl('strip-', g_bplot$layout$name))
k <- 1
for (i in strip_both) {
j <- which(grepl('rect', g_bplot$grobs[[i]]$grobs[[1]]$childrenOrder))
g_bplot$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- colcolors[k]
k <- k+1
}
gbp <- grid.draw(g_bplot)
print(gbp)
}
}
```

## Plot gene count boxplots
### DE Genes

```{r}
pdf(file = "~/computing/scripts/EAPSI_LPS-master/DESeqresults_Pdam/figures/LPSboxplots_geno_upDEGs.pdf", width = 2.8, height = 2.1)
gglistplot_genotype(LPS_ctrl_up_IDs, dds_LPS, res_LPS, stable_samples_LPS)
```
```{r}
pdf(file = "~/computing/scripts/EAPSI_LPS-master/DESeqresults_Pdam/figures/LPSboxplots_HW1_unique.pdf", width = 2.8, height = 2.1)
gglistplot_genotype(HW1_unique, dds_LPS, res_LPS, stable_samples_LPS)
```
```{r}
pdf(file = "~/computing/scripts/EAPSI_LPS-master/DESeqresults_Pdam/figures/LPSboxplots_HW2_unique.pdf", width = 2.8, height = 2.1)
gglistplot_genotype(HW2_unique, dds_LPS, res_LPS, stable_samples_LPS)
```
```{r}
pdf(file = "~/computing/scripts/EAPSI_LPS-master/DESeqresults_Pdam/figures/LPSboxplots_WT1_unique.pdf", width = 2.8, height = 2.1)
gglistplot_genotype(WT1_unique, dds_LPS, res_LPS, stable_samples_LPS)
```
```{r}
pdf(file = "~/computing/scripts/EAPSI_LPS-master/DESeqresults_Pdam/figures/LPSboxplots_WT2_unique.pdf", width = 2.8, height = 2.1)
gglistplot_genotype(WT2_unique, dds_LPS, res_LPS, stable_samples_LPS)
```

### Significant interaction effect genes
```{r}
res_int_HW2 <- as.data.frame(res_LPS_int_HW2) %>% filter(padj < 0.05)
res_int_WT1 <- as.data.frame(res_LPS_int_WT1) %>% filter(padj < 0.05)
res_int_WT2 <- as.data.frame(res_LPS_int_WT2) %>% filter(padj < 0.05)
###
intergenes_HW2 <- res_int_HW2$ID
intergenes_WT1 <- res_int_WT1$ID
intergenes_WT2 <- res_int_WT2$ID
intergenes_WT<- union(res_int_WT1$ID, res_int_WT2$ID)
intergenes <- union(intergenes_WT,  res_int_HW2$ID)
###
pdf(file = "./outputs/DESeq-results/figures/LPSboxplots_interaction-genes.pdf", width = 4, height = 3)
gglistplot_genotype(intergenes, dds_LPS_int, res_LPS_int, stable_samples_LPS)
```

### Similar profile genes
```{r}
pdf(file = "./outputs/DESeq-results/figures/LPSboxplots_sims-up.pdf", width = 4, height = 3)
gglistplot_genotype(sims_up$ID, dds_LPS_int, res_LPS_int, stable_samples_LPS)
```
```{r}
pdf(file = "./outputs/DESeq-results/figures/LPSboxplots_sims-dn.pdf", width = 4, height = 3)
gglistplot_genotype(sims_dn$ID, dds_LPS_int, res_LPS_int, stable_samples_LPS)
```
