---
title: "Stable_DESeq-volcano_Pdam"
author: "Mike Connelly"
date: "10/24/2018"
output: html_document
---
Volcano plots
LPS_Ctrl

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/computing/projects/EAPSI_Pocillopora_LPS")
```
## Setup packages and working directories
```{r packages, error=FALSE, warning=FALSE, message=FALSE}
library("tidyverse")
library("ggplot2")
library("ggrepel")
library("RColorBrewer")
library("calibrate")
```

### LPS vs. Control Differential Expression
```{r}
##Highlight genes that have an absolute fold change > 2 and a padj < 0.01
res_LPS$threshold <- ifelse(res_LPS$padj < 0.01 & res_LPS$log2FoldChange > 0, "Upregulated", ifelse(res_LPS$padj < 0.01 & res_LPS$log2FoldChange < 0, "Downregulated", "NA"))
res_LPS$log10padj <- -log10(res_LPS$padj)
dat_genes_LPS_ctrl <- data.frame(cbind(res_LPS$log2FoldChange, res_LPS$log10padj, res_LPS$threshold), stringsAsFactors = FALSE)
colnames(dat_genes_LPS_ctrl) <- c("log2FoldChange", "log10padj", "threshold")
row.names(dat_genes_LPS_ctrl) <- res_LPS$IDGeneInfo
#dat_genes_LPS_ctrl <- dat_genes_LPS_ctrl[order(dat_genes_LPS_ctrl$log2FoldChange, decreasing = TRUE),]
dat_genes_LPS_ctrl$log2FoldChange <- as.numeric(dat_genes_LPS_ctrl$log2FoldChange)
dat_genes_LPS_ctrl$log10padj <- as.numeric(dat_genes_LPS_ctrl$log10padj)
dat_genes_LPS_ctrl$threshold <- factor(dat_genes_LPS_ctrl$threshold, levels = c("Upregulated", "Downregulated", "NA"), ordered = TRUE)
```
```{r}
class(dat_genes_LPS_ctrl$log2FoldChange)
class(res_LPS$log2FoldChange)
```

```{r, warning = FALSE}
DEGcolors <- c("red", "blue", "dark grey")
pdf(file = "./outputs/DESeq-results/figures/Volcano_LPS-ctrl.pdf", height = 3, width = 2.75)
gVolcano_LPS_ctrl <- ggplot(data=dat_genes_LPS_ctrl, aes(log2FoldChange, log10padj))
gVolcano_LPS_ctrl + geom_point(aes(color = threshold), alpha=0.7, size=2) +
  scale_color_manual(values = DEGcolors) +
  scale_x_continuous(limits = c(-6,6), breaks = seq(-10,10,2)) + 
  ylim(c(0, 50)) +
  xlab("log2 fold change") +
  ylab("-log10 p-value") + 
  #geom_text_repel(data = dat_genes_LPS_ctrl[1:15, ], aes(label = rownames(dat_genes_LPS_ctrl[1:15, ])), color = "black", size = 2.5, box.padding = unit(0.35, "lines")) +
  theme_bw() +
  theme(legend.position = "none", 
        plot.title = element_text(size = 12, hjust = 0, vjust = 1),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 10)) +
  ggtitle("LPS vs. Control Volcano Plot")
```

### LPS vs. Control Differential Expression - normal LFC shrinkage
```{r}
##Highlight genes that have an absolute fold change > 2 and a padj < 0.01
res_LPS_normal$threshold <- ifelse(res_LPS_normal$padj < 0.01 & res_LPS_normal$log2FoldChange > 0, "Upregulated", ifelse(res_LPS_normal$padj < 0.01 & res_LPS_normal$log2FoldChange < -0, "Downregulated", "NA"))
res_LPS_normal$log10padj <- -log10(res_LPS_normal$padj)
dat_genes_LPS_ctrl <- data.frame(cbind(res_LPS_normal$log2FoldChange, res_LPS_normal$log10padj, res_LPS_normal$threshold), stringsAsFactors = FALSE)
colnames(dat_genes_LPS_ctrl) <- c("log2FoldChange", "log10padj", "threshold")
row.names(dat_genes_LPS_ctrl) <- res_LPS_normal$IDGeneInfo
dat_genes_LPS_ctrl <- dat_genes_LPS_ctrl[order(dat_genes_LPS_ctrl$log10padj, decreasing = TRUE),]
dat_genes_LPS_ctrl$log2FoldChange <- as.numeric(dat_genes_LPS_ctrl$log2FoldChange)
dat_genes_LPS_ctrl$log10padj <- as.numeric(dat_genes_LPS_ctrl$log10padj)
dat_genes_LPS_ctrl$threshold <- factor(dat_genes_LPS_ctrl$threshold, levels = c("Upregulated", "Downregulated", "NA"), ordered = TRUE)
```
```{r}
class(dat_genes_LPS_ctrl$log2FoldChange)
class(res_LPS_normal$log2FoldChange)
```
```{r}
r1 <- gsub("\\(.+\\)", "", rownames(dat_genes_LPS_ctrl[1:6, ]))
r1
r2 <- gsub("H.+\\: ", "", r1)
r2
r3 <- gsub("C.+\\: ", "", r2)
r3
r4 <- gsub( "unknown function", "unknown", r3)
r4
rownames(dat_genes_LPS_ctrl[1:6, ])
```
```{r, warning = FALSE}
DEGcolors <- c("red", "blue", "dark grey")
pdf(file = "./outputs/DESeq-results/figures/Volcano_LPS-ctrl_normal_labelled.pdf", height = 2.95, width = 4.25)
gVolcano_LPS_ctrl <- ggplot(data=dat_genes_LPS_ctrl, aes(log2FoldChange, log10padj))
gVolcano_LPS_ctrl + geom_point(aes(color = threshold), alpha=1, size=2) +
  scale_color_manual(values = DEGcolors) +
  scale_x_continuous(limits = c(-3,3), breaks = seq(-3,3,1)) + 
  ylim(c(0, 80)) +
  xlab("log2 fold change") +
  ylab("-log10 p-value") + 
  geom_text_repel(data = dat_genes_LPS_ctrl[1:6, ], aes(label = r4), color = "black", size = 2, box.padding = unit(0.5, "lines")) +
  theme_bw() +
  theme(legend.position = "none") +
  ggtitle("Volcano Plot")
```

### LPS vs. Control Differential Expression - apeglm LFC shrinkage
```{r}
##Highlight genes that have an absolute fold change > 2 and a padj < 0.01
res_LPS_apeglm$threshold <- ifelse(res_LPS_apeglm$padj < 0.01 & res_LPS_apeglm$log2FoldChange > 0, "Upregulated", ifelse(res_LPS_apeglm$padj < 0.01 & res_LPS_apeglm$log2FoldChange < -0, "Downregulated", "NA"))
res_LPS_apeglm$log10padj <- -log10(res_LPS_apeglm$padj)
dat_genes_LPS_ctrl <- data.frame(cbind(res_LPS_apeglm$log2FoldChange, res_LPS_apeglm$log10padj, res_LPS_apeglm$threshold), stringsAsFactors = FALSE)
colnames(dat_genes_LPS_ctrl) <- c("log2FoldChange", "log10padj", "threshold")
row.names(dat_genes_LPS_ctrl) <- res_LPS_apeglm$IDGeneInfo
dat_genes_LPS_ctrl$log2FoldChange <- as.numeric(dat_genes_LPS_ctrl$log2FoldChange)
dat_genes_LPS_ctrl$log10padj <- as.numeric(dat_genes_LPS_ctrl$log10padj)
dat_genes_LPS_ctrl$threshold <- factor(dat_genes_LPS_ctrl$threshold, levels = c("Upregulated", "Downregulated", "NA"), ordered = TRUE)
dat_genes_LPS_ctrl <- dat_genes_LPS_ctrl[order(dat_genes_LPS_ctrl$log10padj, decreasing = TRUE),]
```
```{r}
class(dat_genes_LPS_ctrl$log2FoldChange)
class(res_LPS_apeglm$log2FoldChange)
```

```{r, warning = FALSE}
DEGcolors <- c("red", "blue", "dark grey")
#pdf(file = "./outputs/DESeq-results/figures/Volcano_LPS-ctrl_apeglm.pdf", height = 8.5, width = 11)
gVolcano_LPS_ctrl <- ggplot(data=dat_genes_LPS_ctrl, aes(log2FoldChange, log10padj))
gVolcano_LPS_ctrl + geom_point(aes(color = threshold), alpha=1, size=2) +
  scale_color_manual(values = DEGcolors) +
  scale_x_continuous(limits = c(-4,4), breaks = seq(-4,4,1)) + 
  ylim(c(0, 80)) +
  xlab("log2 fold change") +
  ylab("-log10 p-value") + 
  #geom_text_repel(data = dat_genes_LPS_ctrl[1:12, ], aes(label = rownames(dat_genes_LPS_ctrl[1:12, ])), color = "black", size = 3, box.padding = unit(0.2, "lines")) +
  theme_bw() +
  theme(legend.position = "none") +
  ggtitle("Volcano Plot")
```

### LPS vs. Control Differential Expression for each colony - normal LFC shrinkage
```{r}
##Highlight genes that have an absolute fold change > 2 and a padj < 0.01
res_HW1_normal$threshold <- ifelse(res_HW1_normal$padj < 0.01 & res_HW1_normal$log2FoldChange > 0, "Upregulated", ifelse(res_HW1_normal$padj < 0.01 & res_HW1_normal$log2FoldChange < 0, "Downregulated", "NA"))
res_HW1_normal$log10padj <- -log10(res_HW1_normal$padj)
dat_genes_HW1_normal <- data.frame(cbind(res_HW1_normal$log2FoldChange, res_HW1_normal$log10padj, res_HW1_normal$threshold), stringsAsFactors = FALSE)
colnames(dat_genes_HW1_normal) <- c("log2FoldChange", "log10padj", "threshold")
row.names(dat_genes_HW1_normal) <- res_HW1_normal$IDGeneInfo
#dat_genes_HW1_normal <- dat_genes_HW1_normal[order(dat_genes_HW1_normal$log2FoldChange, decreasing = TRUE),]
dat_genes_HW1_normal$log2FoldChange <- as.numeric(dat_genes_HW1_normal$log2FoldChange)
dat_genes_HW1_normal$log10padj <- as.numeric(dat_genes_HW1_normal$log10padj)
dat_genes_HW1_normal$threshold <- factor(dat_genes_HW1_normal$threshold, levels = c("Upregulated", "Downregulated", "NA"), ordered = TRUE)

##Highlight genes that have an absolute fold change > 2 and a padj < 0.01
res_HW2_normal$threshold <- ifelse(res_HW2_normal$padj < 0.01 & res_HW2_normal$log2FoldChange > 0, "Upregulated", ifelse(res_HW2_normal$padj < 0.01 & res_HW2_normal$log2FoldChange < 0, "Downregulated", "NA"))
res_HW2_normal$log10padj <- -log10(res_HW2_normal$padj)
dat_genes_HW2_normal <- data.frame(cbind(res_HW2_normal$log2FoldChange, res_HW2_normal$log10padj, res_HW2_normal$threshold), stringsAsFactors = FALSE)
colnames(dat_genes_HW2_normal) <- c("log2FoldChange", "log10padj", "threshold")
row.names(dat_genes_HW2_normal) <- res_HW2_normal$IDGeneInfo
#dat_genes_HW2_normal <- dat_genes_HW2_normal[order(dat_genes_HW2_normal$log2FoldChange, decreasing = TRUE),]
dat_genes_HW2_normal$log2FoldChange <- as.numeric(dat_genes_HW2_normal$log2FoldChange)
dat_genes_HW2_normal$log10padj <- as.numeric(dat_genes_HW2_normal$log10padj)
dat_genes_HW2_normal$threshold <- factor(dat_genes_HW2_normal$threshold, levels = c("Upregulated", "Downregulated", "NA"), ordered = TRUE)

##Highlight genes that have an absolute fold change > 2 and a padj < 0.01
res_WT1_normal$threshold <- ifelse(res_WT1_normal$padj < 0.01 & res_WT1_normal$log2FoldChange > 0, "Upregulated", ifelse(res_WT1_normal$padj < 0.01 & res_WT1_normal$log2FoldChange < 0, "Downregulated", "NA"))
res_WT1_normal$log10padj <- -log10(res_WT1_normal$padj)
dat_genes_WT1_normal <- data.frame(cbind(res_WT1_normal$log2FoldChange, res_WT1_normal$log10padj, res_WT1_normal$threshold), stringsAsFactors = FALSE)
colnames(dat_genes_WT1_normal) <- c("log2FoldChange", "log10padj", "threshold")
row.names(dat_genes_WT1_normal) <- res_WT1_normal$IDGeneInfo
#dat_genes_WT1_normal <- dat_genes_WT1_normal[order(dat_genes_WT1_normal$log2FoldChange, decreasing = TRUE),]
dat_genes_WT1_normal$log2FoldChange <- as.numeric(dat_genes_WT1_normal$log2FoldChange)
dat_genes_WT1_normal$log10padj <- as.numeric(dat_genes_WT1_normal$log10padj)
dat_genes_WT1_normal$threshold <- factor(dat_genes_WT1_normal$threshold, levels = c("Upregulated", "Downregulated", "NA"), ordered = TRUE)

##Highlight genes that have an absolute fold change > 2 and a padj < 0.01
res_WT2_normal$threshold <- ifelse(res_WT2_normal$padj < 0.01 & res_WT2_normal$log2FoldChange > 0, "Upregulated", ifelse(res_WT2_normal$padj < 0.01 & res_WT2_normal$log2FoldChange < 0, "Downregulated", "NA"))
res_WT2_normal$log10padj <- -log10(res_WT2_normal$padj)
dat_genes_WT2_normal <- data.frame(cbind(res_WT2_normal$log2FoldChange, res_WT2_normal$log10padj, res_WT2_normal$threshold), stringsAsFactors = FALSE)
colnames(dat_genes_WT2_normal) <- c("log2FoldChange", "log10padj", "threshold")
row.names(dat_genes_WT2_normal) <- res_WT2_normal$IDGeneInfo
#dat_genes_WT2_normal <- dat_genes_WT2_normal[order(dat_genes_WT2_normal$log2FoldChange, decreasing = TRUE),]
dat_genes_WT2_normal$log2FoldChange <- as.numeric(dat_genes_WT2_normal$log2FoldChange)
dat_genes_WT2_normal$log10padj <- as.numeric(dat_genes_WT2_normal$log10padj)
dat_genes_WT2_normal$threshold <- factor(dat_genes_WT2_normal$threshold, levels = c("Upregulated", "Downregulated", "NA"), ordered = TRUE)
```

```{r, warning = FALSE}
DEGcolors <- c("red", "blue", "dark grey")
pdf(file = "./outputs/DESeq-results/figures/Volcano_LPS-ctrl_colonies.pdf", height = 2, width = 2.12)
gVolcano_HW1_normal <- ggplot(data=dat_genes_HW1_normal, aes(log2FoldChange, log10padj))
gVolcano_HW1_normal + geom_point(aes(color = threshold), alpha=1, size=2) +
  scale_color_manual(values = DEGcolors) +
  scale_x_continuous(limits = c(-3,3), breaks = seq(-10,10,2)) + 
  ylim(c(0, 40)) +
  xlab("log2 fold change") +
  ylab("-log10 p-value") + 
  #geom_text_repel(data = dat_genes_LPS_ctrl[1:15, ], aes(label = rownames(dat_genes_LPS_ctrl[1:15, ])), color = "black", size = 2.5, box.padding = unit(0.35, "lines")) +
  theme_bw() + ggtitle("") +
  theme(legend.position = "none",
         axis.text = element_text(size = 10),
        axis.title = element_text(size = 10))

gVolcano_HW2_normal <- ggplot(data=dat_genes_HW2_normal, aes(log2FoldChange, log10padj))
gVolcano_HW2_normal + geom_point(aes(color = threshold), alpha=1, size=2) +
  scale_color_manual(values = DEGcolors) +
  scale_x_continuous(limits = c(-3,3), breaks = seq(-10,10,2)) + 
  ylim(c(0, 40)) +
  xlab("log2 fold change") +
  ylab("-log10 p-value") + 
  #geom_text_repel(data = dat_genes_LPS_ctrl[1:15, ], aes(label = rownames(dat_genes_LPS_ctrl[1:15, ])), color = "black", size = 2.5, box.padding = unit(0.35, "lines")) +
  theme_bw() + ggtitle("") +
  theme(legend.position = "none",
         axis.text = element_text(size = 10),
        axis.title = element_text(size = 10))

gVolcano_WT1_normal <- ggplot(data=dat_genes_WT1_normal, aes(log2FoldChange, log10padj))
gVolcano_WT1_normal + geom_point(aes(color = threshold), alpha=1, size=2) +
  scale_color_manual(values = DEGcolors) +
  scale_x_continuous(limits = c(-3,3), breaks = seq(-10,10,2)) + 
  ylim(c(0, 40)) +
  xlab("log2 fold change") +
  ylab("-log10 p-value") + 
  #geom_text_repel(data = dat_genes_LPS_ctrl[1:15, ], aes(label = rownames(dat_genes_LPS_ctrl[1:15, ])), color = "black", size = 2.5, box.padding = unit(0.35, "lines")) +
  theme_bw() + ggtitle("") +
  theme(legend.position = "none",
         axis.text = element_text(size = 10),
        axis.title = element_text(size = 10))

gVolcano_WT2_normal <- ggplot(data=dat_genes_WT2_normal, aes(log2FoldChange, log10padj))
gVolcano_WT2_normal + geom_point(aes(color = threshold), alpha=1, size=2) +
  scale_color_manual(values = DEGcolors) +
  scale_x_continuous(limits = c(-3,3), breaks = seq(-10,10,2)) + 
  ylim(c(0, 40)) +
  xlab("log2 fold change") +
  ylab("-log10 p-value") + 
  #geom_text_repel(data = dat_genes_LPS_ctrl[1:15, ], aes(label = rownames(dat_genes_LPS_ctrl[1:15, ])), color = "black", size = 2.5, box.padding = unit(0.35, "lines")) +
  theme_bw() + ggtitle("") +
  theme(legend.position = "none",
         axis.text = element_text(size = 10),
        axis.title = element_text(size = 10))
```